### ISSUE TITLE
Corruption using push.

### ISSUE THREAD

**Issue by edt-xx** [jessrud/zbox#3]
First.  Thanks for posting this code.  It is quite helpful.

Looks like the under laying term has some safety issues.  I am seeing quite a bit of corruption using buffer.push.  The front buffer seems fine, its on the term...  I have been force to use a buffer.show function.

pub fn show(buffer: Buffer) (Allocator.Error || ErrorSet.Utf8Encode || ErrorSet.Write)!void {

    // resizing the front buffer naively can lead to artifacting
    // if we do not clear the terminal here.
    if ((buffer.width != front.width) or (buffer.height != front.height)) {
        try term.clear();
        front.clear();
    }

    try front.resize(buffer.height, buffer.width);
    var row: usize = 0;

    // try term.beginSync();
    while (row < buffer.height) : (row += 1) {
       var col: usize = 0;
       try term.cursorTo(row, 0);
       while (col < buffer.width) : (col += 1) {

            const cell = buffer.cell(row, col);
            front.cellRef(row, col).* = cell;

            var codepoint: [4]u8 = undefined;
            const len = try std.unicode.utf8Encode(cell.char, &codepoint);

            try term.sendSGR(cell.attribs);
            try term.send(codepoint[0..len]);
        }
    }
    try term.cursorTo(0,0);  // so any stack traces can be seen
    // try term.endSync();

    try term.flush();
}

Comments/Suggestions
Ed

**Comment by edt-xx** [comment]
The fix for this issue is to change:

hile (row < buffer.height) : (row += 1) {
        var col: usize = 0;
        var last_touched: usize = 0; // out of bounds, can't match col
        while (col < buffer.width) : (col += 1) {

to something like:

hile (row < buffer.height) : (row += 1) {
        var col: usize = 0;
        var last_touched: usize = 999999; // out of bounds, can't match col
        while (col < buffer.width) : (col += 1) {

Since 0 is no longer always out of bounds

**Comment by edt-xx** [comment]
Also we need:

if (last_touched != col)
                try term.cursorTo(row, col);

            last_touched = col+1;

the col+1 will match in the next iteration of the loop and will avoid positioning the cursor

**Comment by jessrud** [comment]
Excellent. Yes, its been minute since I have looked at this stuff, but i remember these bugs vaguely and i get where you are going here.  If you want to make this a pull request go for it, otherwise I'll work this stuff in sometime this week.

**Comment by edt-xx** [comment]
What you have in the branch is exactly what I initially used.  Later change it too:

        var last_touched: usize = buffer.width;      // out of bounds, can't match col

Which is cleaner (wonder if anyone has a display with 99999 columns :-)

I need to send lots to the console quickly while also getting some input.   In prim.zig, I also changed::

    termios.cc[VTIME] = 0;

If would be nice if this could be something to be set in the interface ( display.timout(usize) ) or something along these lines.

**Comment by jessrud** [comment]
yeah those both seem reasonable. Closing for now
